### ISSUE TITLE
Couldn't parse packet type 47 is invalid

### ISSUE THREAD

**Issue by sebirdman** [librespot-org/libmdns#19] opened 2020-12-04 17:31 UTC
Creating bug at request of: https://github.com/librespot-org/librespot/issues/545

running librespot separately like: 

```/usr/bin/librespot --name Snapcast --bitrate 320 --backend pipe --initial-volume 100 --verbose```

Yields:
```
[2020-12-03T21:05:57Z INFO  librespot] librespot 89cafd7 (2020-11-27). Built on 2020-12-03. Build ID: tnGD7Qeu
[2020-12-03T21:05:57Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:44899
[2020-12-03T21:06:02Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:02Z WARN  libmdns::fsm] couldn't parse packet from [fe80::dcde:59ff:fe7e:71e5]:5353: type 47 is invalid
[2020-12-03T21:06:03Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:06Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:06Z WARN  libmdns::fsm] couldn't parse packet from [fe80::dcde:59ff:fe7e:71e5]:5353: type 47 is invalid
[2020-12-03T21:06:11Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:14Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:15Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
[2020-12-03T21:06:15Z WARN  libmdns::fsm] couldn't parse packet from [fe80::dcde:59ff:fe7e:71e5]:5353: type 47 is invalid
[2020-12-03T21:06:16Z WARN  libmdns::fsm] couldn't parse packet from 10.10.1.1:5353: type 47 is invalid
```

this currently breaks librespot and should be addressed. From @ashthespy:

> Type 47 should map to `Next Secure record` from [rfc4034](https://tools.ietf.org/html/rfc4034#section-4)
> Would you open up an issue in `libmdns` for this?
> 
> Either way @willstott101 something to consider?

**Comment by willstott101** [comment] 2020-12-06 12:47
Hm, atm we're vendoring an old version dns-parser, probably about time we switched, to something maintained.

Candidates are probably: https://crates.io/crates/trust-dns-proto and https://crates.io/crates/dns-message-parser

I might also investigate using a higher-level library like https://crates.io/crates/trust-dns-client making libmdns be a completely minimal wrapper to simplify usage.

**Comment by ashthespy** [comment] 2020-12-07 18:11
Ah, I was under the impression it was a written by @plietar back in the day, but now see it's actually a fork of [`tailhook/dns-parser`](https://github.com/tailhook/dns-parser).

Wouldn't it be less work to just add this record into https://github.com/librespot-org/libmdns/blob/e63275fb561c44db4eb73e6af743850c7eefc056/src/dns_parser/enums.rs#L7-L10

And since we (`librespot`) don't actively parse this packet, it would just fall into the `Unknown`  `RData`? But then again, my knowledge here is next to nil :-D

**Comment by willstott101** [comment] 2020-12-07 18:42
I'll have to check but I'd assumed we already ignoring this packet, so all that would do is stop the logging (which is probably helpful anyway). The original issue is about a failure in the discovery of the librespot service, which implies this 47 might be something to respond to.

**Comment by sebirdman** [comment] 2020-12-08 16:33
@willstott101 i may have misdiagnosed the issue, as i thought this message was breaking things for me.

**Comment by 2opremio** [comment] 2021-12-23 17:08
I am still getting these error messages.

```
couldn't parse packet from 10.10.20.61:5353: type 47 is invalid
couldn't parse packet from 10.10.20.63:5353: type 47 is invalid
couldn't parse packet from 10.10.20.64:5353: type 47 is invalid
couldn't parse packet from 10.10.20.57:5353: type 47 is invalid
```

**Comment by rindlerblabla** [comment] 2022-01-12 13:30
So do I.

**Comment by rindlerblabla** [comment] 2022-01-12 13:53
So do I.

**Comment by 2opremio** [comment] 2022-01-12 15:11
I got rid of the problem by switching to avahi in librespot.

**Comment by eljojo** [comment] 2022-03-07 02:29
@2opremio could you explain how?

**Comment by 2opremio** [comment] 2022-03-07 02:56
Enable the `"with-dns-sd"` feature form librespot

**Comment by jonathanicq** [comment] 2022-03-26 11:19
@2opremio 
Can you explain how to do that? 

Thank you in advance

**Comment by 2opremio** [comment] 2022-03-26 19:04
It’s a Cargo feature. There are lots of tutorials of how to build Rust projects on the web.

**Comment by willstott101** [comment] 2022-05-08 14:44
I've not confirmed this is fixed - didn't intend github to auto close it.

**Comment by willstott101** [comment] 2022-05-08 14:46
I would appreciate it if someone affected by this could test that the current `main`  branch and see if the solution is as easy as https://github.com/librespot-org/libmdns/commit/ca9b28946a111872a63e16a1cc306fd9492cad44.

If that doesn't work, a copy of one of these packets would also be very helpful.

**Comment by Gnarflord** [comment] 2022-05-19 17:01
Hi there,
I can confirm, that this completely fixes the issue for me, thank you so much!

I'm using librespot, a Spotify API player, that communicates to other devices via mdns. If I compile the package with libmdns version=0.6 I'm getting spammed with warnings, as other devices (smart IOT power plugs in my case) use this packet type 47.

If I compile it with version=0.7 I get no warnings at all, while previously about >1000 daily warning messages ended in my journal :))

**Comment by willstott101** [comment] 2022-05-19 18:26
That's great. Thanks for confirming, and for the librespot PR.

**Closed by willstott101** 2022-05-19 18:26 UTC
